# Generated by Django 2.2.14 on 2020-12-04 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201203_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='alerts',
        ),
    ]
