# Generated by Django 2.2.14 on 2020-12-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('verbose_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(max_length=50)),
                ('developer', models.EmailField(max_length=254)),
                ('approved', models.BooleanField(default=False)),
                ('ours', models.BooleanField(default=False)),
                ('details', models.TextField()),
                ('src_destination', models.URLField()),
                ('downloads', models.IntegerField(default=0)),
                ('permissions', models.ManyToManyField(related_name='permissions', to='plugins.Permission')),
            ],
        ),
        migrations.AddField(
            model_name='permission',
            name='plugins',
            field=models.ManyToManyField(blank=True, to='plugins.Plugin'),
        ),
    ]
