# Generated by Django 2.2.14 on 2020-12-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plugins', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='stores_granted',
            field=models.ManyToManyField(blank=True, to='store.Store'),
        ),
    ]
