# Generated by Django 2.2.14 on 2020-12-04 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('opt_address', models.TextField(blank=True, null=True)),
                ('card_number', models.CharField(max_length=24)),
                ('card_name', models.CharField(max_length=24)),
                ('card_cvv', models.CharField(max_length=24)),
                ('card_exp', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Billing Addresses',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_id', models.CharField(blank=True, max_length=50)),
                ('avatar', models.FileField(blank=True, null=True, upload_to='profile/')),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=150)),
                ('bank_acct_name', models.CharField(max_length=150)),
                ('bank_acct_num', models.CharField(max_length=30)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.URLField()),
                ('name', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=200)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Merchant')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('opt_address', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shipping Addresses',
            },
        ),
    ]
